# Tensors

[PyTorch Tensor Tutorial](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)

In [1]:
import torch
import numpy as np

* Initializing tensors

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [7]:
x_ones = torch.ones_like(x_data)
print(x_ones)
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.5474, 0.7987],
        [0.3440, 0.0952]])


In [10]:
# Generating

shape = (2,3)
rand_tensor = torch.rand(shape)
print(rand_tensor)
ones_tensor = torch.ones(shape)
print(ones_tensor)
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)

tensor([[0.2431, 0.5374, 0.7057],
        [0.8792, 0.9421, 0.4673]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


* Attributes of a Tensor

In [12]:
tensor = torch.rand(3,4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


* Operations on Tensors

In [13]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
else:
    print("You're a poor CPU guy like me :þ")

You're a poor CPU guy like me :þ


In [16]:
# Slicing and selecting

tensor = torch.rand(4,4)
print(tensor)
print()

print("First row:",tensor[0])
print("Last row:", tensor[-1])
print("First col:",tensor[:,0])
print("Last col:",tensor[:,-1])

tensor[:,1] = 0
print("Col 1 all 0s:",tensor)

tensor([[0.4942, 0.4344, 0.2940, 0.9807],
        [0.0225, 0.2089, 0.7168, 0.9058],
        [0.2143, 0.8950, 0.5594, 0.7579],
        [0.1248, 0.0787, 0.8696, 0.0268]])

First row: tensor([0.4942, 0.4344, 0.2940, 0.9807])
Last row: tensor([0.1248, 0.0787, 0.8696, 0.0268])
First col: tensor([0.4942, 0.0225, 0.2143, 0.1248])
Last col: tensor([0.9807, 0.9058, 0.7579, 0.0268])
Col 1 all 0s: tensor([[0.4942, 0.0000, 0.2940, 0.9807],
        [0.0225, 0.0000, 0.7168, 0.9058],
        [0.2143, 0.0000, 0.5594, 0.7579],
        [0.1248, 0.0000, 0.8696, 0.0268]])


In [22]:
# Concatenate

# Rows
t1 = torch.cat([tensor, tensor], dim=1)
print(t1)
print()

# Columns
t2 = torch.cat([tensor, tensor])
print(t2)

tensor([[0.4942, 0.0000, 0.2940, 0.9807, 0.4942, 0.0000, 0.2940, 0.9807],
        [0.0225, 0.0000, 0.7168, 0.9058, 0.0225, 0.0000, 0.7168, 0.9058],
        [0.2143, 0.0000, 0.5594, 0.7579, 0.2143, 0.0000, 0.5594, 0.7579],
        [0.1248, 0.0000, 0.8696, 0.0268, 0.1248, 0.0000, 0.8696, 0.0268]])

tensor([[0.4942, 0.0000, 0.2940, 0.9807],
        [0.0225, 0.0000, 0.7168, 0.9058],
        [0.2143, 0.0000, 0.5594, 0.7579],
        [0.1248, 0.0000, 0.8696, 0.0268],
        [0.4942, 0.0000, 0.2940, 0.9807],
        [0.0225, 0.0000, 0.7168, 0.9058],
        [0.2143, 0.0000, 0.5594, 0.7579],
        [0.1248, 0.0000, 0.8696, 0.0268]])


In [31]:
# Arithmetic operations

# Tensor like matrix product
y1 = tensor @ tensor.T # T transpose
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(y1)
print(y2)
print(y3)
print(y1==y2)
print(y1==y3)
print()

tensor([[1.2924, 1.1102, 1.0136, 0.3436],
        [1.1102, 1.3348, 1.0923, 0.6505],
        [1.0136, 1.0923, 0.9332, 0.5335],
        [0.3436, 0.6505, 0.5335, 0.7725]])
tensor([[1.2924, 1.1102, 1.0136, 0.3436],
        [1.1102, 1.3348, 1.0923, 0.6505],
        [1.0136, 1.0923, 0.9332, 0.5335],
        [0.3436, 0.6505, 0.5335, 0.7725]])
tensor([[1.2924, 1.1102, 1.0136, 0.3436],
        [1.1102, 1.3348, 1.0923, 0.6505],
        [1.0136, 1.0923, 0.9332, 0.5335],
        [0.3436, 0.6505, 0.5335, 0.7725]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])



In [32]:
# Tensor like element by element product.
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(z1)
print(z2)
print(z3)
print(z1==z2)
print(z1==z3)

tensor([[2.4419e-01, 0.0000e+00, 8.6434e-02, 9.6181e-01],
        [5.0514e-04, 0.0000e+00, 5.1387e-01, 8.2043e-01],
        [4.5905e-02, 0.0000e+00, 3.1290e-01, 5.7441e-01],
        [1.5565e-02, 0.0000e+00, 7.5622e-01, 7.1809e-04]])
tensor([[2.4419e-01, 0.0000e+00, 8.6434e-02, 9.6181e-01],
        [5.0514e-04, 0.0000e+00, 5.1387e-01, 8.2043e-01],
        [4.5905e-02, 0.0000e+00, 3.1290e-01, 5.7441e-01],
        [1.5565e-02, 0.0000e+00, 7.5622e-01, 7.1809e-04]])
tensor([[2.4419e-01, 0.0000e+00, 8.6434e-02, 9.6181e-01],
        [5.0514e-04, 0.0000e+00, 5.1387e-01, 8.2043e-01],
        [4.5905e-02, 0.0000e+00, 3.1290e-01, 5.7441e-01],
        [1.5565e-02, 0.0000e+00, 7.5622e-01, 7.1809e-04]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [35]:
# Single-element tensors
agg = tensor.sum()
print(agg, type(agg))
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(5.9667) <class 'torch.Tensor'>
5.966668605804443 <class 'float'>


In [37]:
# Simple arithmetic operation by element.
print(tensor)
tensor.add_(13)
print(tensor)

tensor([[0.4942, 0.0000, 0.2940, 0.9807],
        [0.0225, 0.0000, 0.7168, 0.9058],
        [0.2143, 0.0000, 0.5594, 0.7579],
        [0.1248, 0.0000, 0.8696, 0.0268]])
tensor([[13.4942, 13.0000, 13.2940, 13.9807],
        [13.0225, 13.0000, 13.7168, 13.9058],
        [13.2143, 13.0000, 13.5594, 13.7579],
        [13.1248, 13.0000, 13.8696, 13.0268]])


* Bridge with NumPy

Tensors and NumPy can share the same space memory, i.e, if you modify the tensor the ndarray are going to be modified and viceversa.

In [38]:
t = torch.ones(5)
n = t.numpy()
print(t)
print(n)
print()

t.add_(1)
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]



In [39]:
n = np.ones(5)
t = torch.from_numpy(n)
print(t)
print(n)
print()

np.add(n, 1, out=n)
print(t)
print(n)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[1. 1. 1. 1. 1.]

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
